### PR TITLE
BACKLOG-22134: Update version and add missing Nexus env var

### PR DESCRIPTION
**Pull request by rknj**
## JIRA

https://jira.jahia.org/browse/BACKLOG-22134

### CODE REVIEW

**Review by gflores-jahia — COMMENTED** [review]
Probably need a signature update as well

**Comment by rknj** [comment]
the signature has not been triggered by JahiaReleaseTool so I think we're good

**Comment by gflores-jahia** [comment]
It was updated from recent change here https://github.com/Jahia/jcontent/pull/1208

**Comment by rknj** [comment]
I did it manually

**Review by gflores-jahia — DISMISSED** [review]
might be 401 due to staging repos

**Review by gflores-jahia — APPROVED** [review]

**Pull request merged**
